version: '3.7'
services: 
  ui:
    build:
      context: ./led-frontend
      target: 'develop-stage'
    env_file:
      - .env      
    ports:
    - '8088:8088'
    volumes:
    - './led-frontend:/app'
    command: /bin/sh -c "yarn && quasar dev"

  api:
    build:
      context: ./led-api-server
      dockerfile: ./deploy/Dockerfile
      target: 'develop-stage'
    env_file:
      - .env      
    ports:
      - "8888:8000"
    volumes:
      - type: bind
        source: ./led-api-server
        target: /home/docker/code
    command: >-
      bash -c "
      cd /home/docker/code/app
      && python3 manage.py migrate
      && python3 manage.py runserver 0.0.0.0:8000 
      "
      