version: '3.7'
services: 
  zmq:
    privileged: true
    build:
      context: ./led-zmq-server
      target: 'develop-stage'
    volumes:
      - type: bind
        source: ./led-zmq-server
        target: /home/docker/code
    ports:
    - '5555:5555'

  ui:
    build:
      context: ./led-frontend
      target: 'develop-stage'
      args:
        - HOSTNAME=localhost
    env_file:
      - .env      
    environment:
      - HOSTNAME=localhost
    ports:
    - '8088:8088'
    volumes:
    - './led-frontend:/app'
    command: /bin/sh -c "yarn && quasar dev"

  api:
    build:
      context: ./led-api-server
      dockerfile: ./deploy/Dockerfile
      target: 'develop-stage'
    env_file:
      - .env      
    environment:
      - HOSTNAME=localhost
      - DJANGO_SECRET_KEY=unsafe_key
    ports:
      - "8888:8000"
    volumes:
      - type: bind
        source: ./led-api-server
        target: /home/docker/code
    command: >-
      bash -c "
      service cron start
      && cd /home/docker/code/app
      && python3 manage.py migrate
      && python3 manage.py runserver 0.0.0.0:8000 
      "
      