version: '3.7'
services: 
  ui:
    restart: always
    build:
      context: ./led-frontend
      target: 'production-stage'
      args:
        - HOSTNAME=$HOSTNAME
        - WLED_WS=$WLED_WS
        - WLED_UI=$WLED_UI
        - WLED_API=$WLED_API
        - MOPIDY_WS=$MOPIDY_WS
        - MOPIDY_UI=$MOPIDY_UI
        - MOPIDY_API=$MOPIDY_API
    env_file:
      - .env
    ports:
    - '80:80'

  api:
    restart: always
    build:
      context: ./led-api-server
      dockerfile: ./deploy/Dockerfile
      target: 'production-stage'
    env_file:
      - .env
    ports:
      - '8888:8888'
