# Generated by Django 3.1.2 on 2021-02-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0007_alarmconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alarm',
        ),
    ]
