# Generated by Django 3.1.7 on 2021-03-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0008_delete_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmconfig',
            name='shuffle',
            field=models.BooleanField(default=False, help_text='Enable shuffling of playlist'),
        ),
    ]
